version: '3'

services:
 next-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-web
    restart: always
    volumes:
      - ./:/app
    ports:
      - "3000:3000"